package main

import (
	"fmt"
	"google.golang.org/protobuf/reflect/protoreflect"
	"log"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const ()

var methodSets = make(map[string]int)

// generateFile generates a _http.pb.go file containing kratos errors definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File, omitempty bool, omitemptyPrefix string) *protogen.GeneratedFile {
	if len(file.Messages) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + ".pb.ts"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-ts-iface. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-ts-iface %s", release))
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()

	generateFileContent(gen, file, g)
	return g
}

// generateFileContent generates the kratos errors definitions, excluding the package statement.
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the kratos package it is being compiled against.")
	g.P()

	imports := file.Desc.Imports()
	for i := 0; i < imports.Len(); i++ {
		imp := imports.Get(i)
		prefix := imp.Path()
		if prefix == "google/api/annotations.proto" {
			continue
		}
		if prefix == "google/protobuf/any.proto" {
			continue
		}

		if prefix == "google/protobuf/timestamp.proto" {
			prefix = "../google/protobuf/timestamp.proto"
		}

		if ext := path.Ext(prefix); ext == ".proto" || ext == ".protodevel" {
			prefix = prefix[:len(prefix)-len(ext)]
		}
		_, name := path.Split(prefix)
		g.P("import * as " + name + " from \"./" + prefix + ".pb\"")
	}
	g.P()

	for _, message := range file.Messages {
		genMessages(gen, file, g, message)
	}
}

func genMessages(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, message *protogen.Message) {
	for _, item := range message.Messages {
		genMessages(gen, file, g, item)
	}

	if message.Desc.Options().(*descriptorpb.MessageOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	// HTTP Server.
	sd := &messagesDesc{
		MessageType: message.GoIdent.GoName,
		MessageName: string(message.Desc.FullName()),
		Metadata:    file.Desc.Path(),
	}
	for _, field := range message.Fields {
		sd.Fields = append(sd.Fields, buildFieldDesc(gen, file, g, field))
	}

	g.P(sd.execute())
	g.P()
}

func buildFieldDesc(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, m *protogen.Field) *fieldDesc {
	comment := m.Comments.Leading.String() + m.Comments.Trailing.String()
	if comment != "" {
		comment = "// " + m.GoName + strings.TrimPrefix(strings.TrimSuffix(comment, "\n"), "//")
	}

	return &fieldDesc{
		Name:         m.GoName,
		OriginalName: string(m.Desc.Name()),
		Num:          methodSets[m.GoName],
		Comment:      comment,
		Kind:         "(" + getKind(gen, file, g, m.Desc) + " | null)",
	}
}

func getKind(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, d protoreflect.FieldDescriptor) string {

	text := ""
	switch d.Kind() {
	case protoreflect.BoolKind:
		text = "boolean"
	case protoreflect.EnumKind:
		//text = string(d.Enum().Name())
		text = "number"
	case protoreflect.Int32Kind:
		text = "number"
	case protoreflect.Sint32Kind:
		text = "number"
	case protoreflect.Uint32Kind:
		text = "number"
	case protoreflect.Int64Kind:
		text = "bigint"
	case protoreflect.Sint64Kind:
		text = "bigint"
	case protoreflect.Uint64Kind:
		text = "bigint"
	case protoreflect.Sfixed32Kind:
		text = "number"
	case protoreflect.Fixed32Kind:
		text = "number"
	case protoreflect.FloatKind:
		text = "number"
	case protoreflect.Sfixed64Kind:
		text = "number"
	case protoreflect.Fixed64Kind:
		text = "number"
	case protoreflect.DoubleKind:
		text = "number"
	case protoreflect.StringKind:
		text = "string"
	case protoreflect.BytesKind:
		text = "string"
	case protoreflect.MessageKind:
		if d.IsMap() {
			text = "Record<" + getKind(gen, file, g, d.MapKey()) + "," + getKind(gen, file, g, d.MapValue()) + ">"
		} else {
			if d.Message().Name() == "Any" {
				text = "any"
			} else {
				name := ""
				if file == nil {
					log.Printf("if file == nil{\n")
				}
				if d.Message().ParentFile() != nil && file.Desc != d.Message().ParentFile() {
					prefix := d.Message().ParentFile().Path()
					_, name = path.Split(prefix[:len(prefix)-len(path.Ext(prefix))])
					name += "."
				}

				text = name + getMessageName(d.Message())
			}
		}
	case protoreflect.GroupKind:
		text = "string"
	default:
		text = fmt.Sprintf("<unknown:%d>", d.Kind())
	}
	if d.IsList() {
		text += "[]"
	}
	return text
}

func getMessageName(message protoreflect.MessageDescriptor) string {
	name := string(message.Name())
	name = strings.ToUpper(name[:1]) + name[1:]

	temp := message.Parent()
	if nil != temp {
		if parent, ok := temp.(protoreflect.MessageDescriptor); ok {
			name = getMessageName(parent) + name
		}
	}
	return name
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

const deprecationComment = "// Deprecated: Do not use."
